# -*- coding: utf-8 -*-
"""lab03.cu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkRyGsImb54bmyEwcOZdXWX8YeYxBLNG
"""

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile lab03.cu
# #include <stdio.h>
# #include <stdlib.h>
# #include <cuda_runtime.h>
# 
# // Kernel function
# __global__ void my_kernel(int N, float A, float *x, float *y, float *r)
# {
#     int index = blockIdx.x * blockDim.x + threadIdx.x;
#     if (index < N)
#         r[index] = A * x[index] + y[index];
# }
# 
# int main()
# {
#     // 1. Өгөгдлийн хэмжээ
#     int N = 1 << 20;   // 2^20 = 1048576 element
#     float A = 2.0f;
#     size_t size = N * sizeof(float);
# 
#     // 2. Host memory
#     float *h_x = (float*)malloc(size);
#     float *h_y = (float*)malloc(size);
#     float *h_r = (float*)malloc(size);
# 
#     for (int i = 0; i < N; i++)
#     {
#         h_x[i] = 1.0f;
#         h_y[i] = 2.0f;
#     }
# 
#     // 3. Device memory
#     float *d_x, *d_y, *d_r;
#     cudaMalloc((void**)&d_x, size);
#     cudaMalloc((void**)&d_y, size);
#     cudaMalloc((void**)&d_r, size);
# 
#     // 4. CUDA events for timing
#     cudaEvent_t total_start, total_stop;
#     cudaEvent_t h2d_start, h2d_stop;
#     cudaEvent_t kernel_start, kernel_stop;
#     cudaEvent_t d2h_start, d2h_stop;
# 
#     cudaEventCreate(&total_start);
#     cudaEventCreate(&total_stop);
#     cudaEventCreate(&h2d_start);
#     cudaEventCreate(&h2d_stop);
#     cudaEventCreate(&kernel_start);
#     cudaEventCreate(&kernel_stop);
#     cudaEventCreate(&d2h_start);
#     cudaEventCreate(&d2h_stop);
# 
#     int threads = 256;
#     int blocks = (N + threads - 1) / threads;
# 
#     // ================== TOTAL TIME START ==================
#     cudaEventRecord(total_start);
# 
#     // 5. Host to Device copy
#     cudaEventRecord(h2d_start);
#     cudaMemcpy(d_x, h_x, size, cudaMemcpyHostToDevice);
#     cudaMemcpy(d_y, h_y, size, cudaMemcpyHostToDevice);
#     cudaEventRecord(h2d_stop);
#     cudaEventSynchronize(h2d_stop);
# 
#     // 6. Kernel launch
#     cudaEventRecord(kernel_start);
#     my_kernel<<<blocks, threads>>>(N, A, d_x, d_y, d_r);
#     cudaEventRecord(kernel_stop);
#     cudaEventSynchronize(kernel_stop);
# 
#     // 7. Device to Host copy
#     cudaEventRecord(d2h_start);
#     cudaMemcpy(h_r, d_r, size, cudaMemcpyDeviceToHost);
#     cudaEventRecord(d2h_stop);
#     cudaEventSynchronize(d2h_stop);
# 
#     cudaEventRecord(total_stop);
#     cudaEventSynchronize(total_stop);
#     // ================== TOTAL TIME STOP ==================
# 
#     // 8. Elapsed times
#     float total_ms = 0.0f, h2d_ms = 0.0f, kernel_ms = 0.0f, d2h_ms = 0.0f;
#     cudaEventElapsedTime(&total_ms, total_start, total_stop);
#     cudaEventElapsedTime(&h2d_ms, h2d_start, h2d_stop);
#     cudaEventElapsedTime(&kernel_ms, kernel_start, kernel_stop);
#     cudaEventElapsedTime(&d2h_ms, d2h_start, d2h_stop);
# 
#     // 9. Verify result
#     bool bl = true;
#     for (int i = 0; i < N; i++)
#     {
#         if (h_r[i] != 4.0f)
#         {
#             bl = false;
#             break;
#         }
#     }
# 
#     if (!bl)
#         printf("NOT OK\n");
#     else
#         printf("OK\n");
# 
#     // 10. Bandwidth calculations
#  float h2d_bytes = 2 * N * sizeof(float);
# float d2h_bytes = 1 * N * sizeof(float);
# float total_bytes = h2d_bytes + d2h_bytes;
# 
#     float h2d_bandwidth = h2d_bytes / (h2d_ms / 1000.0f) / 1e9;
#     float d2h_bandwidth = d2h_bytes / (d2h_ms / 1000.0f) / 1e9;
#     float total_bandwidth = total_bytes / (total_ms / 1000.0f) / 1e9;
# 
#     // 11. Print results
#     printf("N = %d\n", N);
#     printf("Total time      = %f ms\n", total_ms);
#     printf("H2D time        = %f ms\n", h2d_ms);
#     printf("GPU time        = %f ms\n", kernel_ms);
#     printf("D2H time        = %f ms\n", d2h_ms);
#     printf("H2D bandwidth   = %f GB/s\n", h2d_bandwidth);
#     printf("D2H bandwidth   = %f GB/s\n", d2h_bandwidth);
#     printf("Total bandwidth = %f GB/s\n", total_bandwidth);
# 
#     // 12. Free memory
#     cudaFree(d_x);
#     cudaFree(d_y);
#     cudaFree(d_r);
# 
#     free(h_x);
#     free(h_y);
#     free(h_r);
# 
#     cudaEventDestroy(total_start);
#     cudaEventDestroy(total_stop);
#     cudaEventDestroy(h2d_start);
#     cudaEventDestroy(h2d_stop);
#     cudaEventDestroy(kernel_start);
#     cudaEventDestroy(kernel_stop);
#     cudaEventDestroy(d2h_start);
#     cudaEventDestroy(d2h_stop);
# 
#     return 0;
# }

!nvcc lab03.cu -o lab03
!./lab03